// AUTO-GENERATED by scripts/build-tw5-vendor.ts — do not edit.
// Update TW5_VERSION in build-tw5-vendor.ts and re-run build:tw5-vendor to upgrade.

export const TW5_VERSION = "5.4.1-prerelease";

/** Filename of the vendored TW5 core blob in lararium-tw5/tw5-core/. */
export const TW5_CORE_SCRIPT_FILENAME = "tiddlywikicore-5.4.1-prerelease.js";

/** Absolute path to the lararium-tw5/tw5-core/ directory (build artifact, gitignored). */
export const TW5_CORE_DIR = new URL("../tw5-core", import.meta.url).pathname;
