/**
 * build-tw5-vendor.ts — render TW5 core JS and store it in lararium-tw5/tw5-core/.
 *
 * The blob is seeded into the LarariumDoc at node boot; browser peers receive it
 * via Automerge sync (web3 path — no static HTTP serve of this file).
 *
 * Generates two artifacts:
 *   1. packages/lararium-tw5/tw5-core/tiddlywikicore-<version>.js
 *      TW5's prebuilt browser bundle — seeder source of truth.
 *   2. packages/lararium-tw5/src/generated-tw5-version.ts
 *      Exports TW5_VERSION, TW5_CORE_SCRIPT_FILENAME, TW5_CORE_DIR.
 *
 * Usage:
 *   pnpm --filter @lararium/tw5 run build:tw5-vendor
 *
 * Pinned version: update TW5_VERSION below and re-run to upgrade.
 */

import { writeFileSync, mkdirSync } from "fs";
import { join, resolve, relative, dirname } from "path";
import { fileURLToPath } from "url";
import { createRequire } from "module";
const __dirname = fileURLToPath(new URL(".", import.meta.url));
const _require = createRequire(import.meta.url);

// Re-genesis sources TW5 from the amorphous-dreams/TiddlyWiki5 SUBMODULE (workspace-linked as
// `tiddlywiki`), not an npm pin — the version tracks the fork automatically across branches/PRs.
const TW5_VERSION = _require("tiddlywiki/package.json").version as string;
const TW5_SCRIPT_FILENAME = `tiddlywikicore-${TW5_VERSION}.js`;

// scripts/ → lararium-tw5/ → packages/ → monorepo root
const MONOREPO_ROOT = dirname(dirname(dirname(__dirname)));
const TW5_CORE_DIR  = join(MONOREPO_ROOT, "packages/lararium-tw5/tw5-core");
const CORE_JS_TW5   = join(TW5_CORE_DIR, TW5_SCRIPT_FILENAME);
const VERSION_TS_OUT = resolve(__dirname, "../src/generated-tw5-version.ts");

// ---------------------------------------------------------------------------
// Step 1 — Generate tiddlywikicore-<version>.js using TW5's render pipeline
// ---------------------------------------------------------------------------

console.log(`build-tw5-vendor: generating ${TW5_SCRIPT_FILENAME} via TW5 render pipeline…`);

const tw = _require("tiddlywiki");
const path = _require("path");
const fs = _require("fs");

const tmpOut = join(MONOREPO_ROOT, ".tw5-vendor-tmp");
mkdirSync(tmpOut, { recursive: true });

await new Promise<void>((resolve_p, reject) => {
  const instance = tw.TiddlyWiki();
  const editionsEmpty = path.resolve(
    dirname(_require.resolve("tiddlywiki")),
    "../../editions/empty",
  );
  instance.boot.argv = [
    editionsEmpty,
    "--rendertiddler", "$:/core/templates/tiddlywiki5.js",
    join(tmpOut, TW5_SCRIPT_FILENAME),
    "text/plain",
  ];
  instance.boot.boot(() => {
    const generated = join(tmpOut, TW5_SCRIPT_FILENAME);
    if (!fs.existsSync(generated)) {
      reject(new Error(`TW5 render did not produce ${generated}`));
      return;
    }
    mkdirSync(TW5_CORE_DIR, { recursive: true });
    fs.copyFileSync(generated, CORE_JS_TW5);
    // cleanup tmp
    fs.rmSync(tmpOut, { recursive: true, force: true });
    resolve_p();
  });
});

const sizeKb = Math.round(fs.statSync(CORE_JS_TW5).size / 1024);
console.log(`build-tw5-vendor: wrote ${CORE_JS_TW5} (${sizeKb} kB)`);

// ---------------------------------------------------------------------------
// Step 2 — Generate generated-tw5-version.ts
// ---------------------------------------------------------------------------

const versionTs = `\
// AUTO-GENERATED by scripts/build-tw5-vendor.ts — do not edit.
// Update TW5_VERSION in build-tw5-vendor.ts and re-run build:tw5-vendor to upgrade.

export const TW5_VERSION = "${TW5_VERSION}";

/** Filename of the vendored TW5 core blob in lararium-tw5/tw5-core/. */
export const TW5_CORE_SCRIPT_FILENAME = "${TW5_SCRIPT_FILENAME}";

/** Absolute path to the lararium-tw5/tw5-core/ directory (build artifact, gitignored). */
export const TW5_CORE_DIR = new URL("../tw5-core", import.meta.url).pathname;
`;

writeFileSync(VERSION_TS_OUT, versionTs, "utf-8");
console.log(`build-tw5-vendor: wrote ${relative(process.cwd(), VERSION_TS_OUT)}`);

// ---------------------------------------------------------------------------
// Done — note: generated-tw5-core-modules.ts is no longer needed and can be
// deleted once serve.ts + LarariumTW5 are wired to the external core script.
// ---------------------------------------------------------------------------

console.log(`build-tw5-vendor: done. Pin: tiddlywiki@${TW5_VERSION} → ${TW5_SCRIPT_FILENAME}`);
