#!/usr/bin/env node
/**
 * gen_cli_verbs — emit fixtures/cli-verbs.json from the ACTUAL `lares` command table.
 *
 * Derives the verb list from the built `COMMAND_NAMES` export (packages/lares-cli), so the
 * fixture never drifts from the real CLI surface: re-run after adding/renaming a command.
 * YIN's three-way parity test (CLI command-table ↔ MCP tool-set ↔ VERB_SEATS) reads the output.
 *
 * The isomorphism (operator ruling): `lares`-CLI ↔ `lares`-MCP across the WHOLE verb-set. The six
 * lifecycle tools mirror today; every other verb reads NOT-YET-MIRRORED (the MCP surface grows into
 * it), never permanently CLI-only. `cli_forms` maps each MCP tool name to its CLI spelling — the
 * three sensorium mirrors ride sub-verbs (`sensorium status`, `worldline kapae`, `worldline un-kapae`).
 *
 * Usage:  node scripts/gen_cli_verbs.mjs        (writes fixtures/cli-verbs.json)
 *         node scripts/gen_cli_verbs.mjs --check (fails if the on-disk fixture drifts)
 *
 * Meme: lar:///ha.ka.ba/lararium/sensorium/cli-verbs-fixture
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const CLI_DIST = resolve(HERE, "../../lares-cli/dist/src/bin/lares.js");
const OUT = join(HERE, "fixtures", "cli-verbs.json");

// The MCP lifecycle tool names (mirror YIN's py `LIFECYCLE_VERBS`) → their CLI spelling. After the
// radical two-door collapse EVERY sovereign lifecycle tool mirrors through the one `sense` door — one
// host, no top-level twins. `harvest` mirrors the SOVEREIGN pour (`sense pour`), never the guest miner.
const CLI_FORMS = {
  harvest:   "sense pour",
  recall:    "sense recall",
  status:    "sense status",
  worldline: "sense worldline",
  kapae:     "sense worldline kapae",
  un_kapae:  "sense worldline un-kapae",
};
// The CLI TOP-LEVEL verbs that HOST a mirror — DERIVED from the cli_forms value-heads (single source,
// never drifts): `sensorium status` → sensorium, `worldline kapae` → worldline, harvest → harvest. The
// coverage partition rides these CLI-form heads, NOT the MCP tool-names (kapae/un_kapae are worldline
// sub-verbs, not top-level verbs; status mirrors under `sensorium`, not bare `status` = node-health).
const MIRROR_HOSTS = new Set(Object.values(CLI_FORMS).map((f) => f.split(" ")[0]));

async function loadCommandNames() {
  const mod = await import(pathToFileURL(CLI_DIST).href);
  if (!Array.isArray(mod.COMMAND_NAMES)) {
    throw new Error(`COMMAND_NAMES not found in ${CLI_DIST} — build lares-cli first (pnpm -C packages/lares-cli build)`);
  }
  return mod.COMMAND_NAMES;
}

function buildFixture(verbs) {
  const mirrored = Object.keys(CLI_FORMS); // MCP tool names — set-equal to py LIFECYCLE_VERBS (the MCP anchor)
  const mirrorHosts = [...MIRROR_HOSTS].sort(); // CLI top-level verbs hosting a mirror (the coverage partition)
  const notYet = verbs.filter((v) => !MIRROR_HOSTS.has(v));
  return {
    _doc: "Isomorphism fixture — the `lares` CLI verb surface for the three-way parity test " +
      "(CLI command-table ↔ MCP tool-set ↔ VERB_SEATS). `mirrored` = the MCP tool-names that mirror " +
      "today (set-equal to py LIFECYCLE_VERBS, the MCP anchor); `cli_forms` maps each MCP tool to its " +
      "CLI spelling (some ride sub-verbs); `mirror_hosts` = the CLI TOP-LEVEL verbs those spellings land " +
      "on (the coverage partition); `not_yet_mirrored` = verbs − mirror_hosts (the surface grows into " +
      "them). Invariant: mirror_hosts ∪ not_yet_mirrored == verbs. Generated by gen_cli_verbs.mjs.",
    verbs,
    mirrored,
    cli_forms: CLI_FORMS,
    mirror_hosts: mirrorHosts,
    not_yet_mirrored: notYet,
  };
}

const verbs = await loadCommandNames();
const fixture = buildFixture(verbs);
const rendered = JSON.stringify(fixture, null, 2) + "\n";

if (process.argv.includes("--check")) {
  let onDisk = "";
  try { onDisk = readFileSync(OUT, "utf8"); } catch { /* absent → drift */ }
  if (onDisk !== rendered) {
    console.error("cli-verbs.json DRIFT — re-run `node scripts/gen_cli_verbs.mjs` to sync.");
    process.exit(1);
  }
  console.log("cli-verbs.json up to date.");
} else {
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, rendered);
  console.log(`wrote ${OUT} — ${verbs.length} verbs, ${fixture.mirrored.length} mirrored.`);
}
