/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 40
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 20
#define ALIAS_COUNT 0
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 8
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT_LT_TILDE = 1,
  anon_sym_GT_GT = 2,
  anon_sym_LT_LT_TILDE_SLASH = 3,
  sym_sigil_body = 4,
  aux_sym_fenced_block_token1 = 5,
  aux_sym_fenced_block_token2 = 6,
  aux_sym_fenced_block_token3 = 7,
  sym_heading = 8,
  sym_comment = 9,
  sym_blank_line = 10,
  sym_text_line = 11,
  sym_document = 12,
  sym__block = 13,
  sym_ahu_block = 14,
  sym_sigil = 15,
  sym_sigil_close = 16,
  sym_fenced_block = 17,
  aux_sym_document_repeat1 = 18,
  aux_sym_fenced_block_repeat1 = 19,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_LT_TILDE] = "<<~",
  [anon_sym_GT_GT] = ">>",
  [anon_sym_LT_LT_TILDE_SLASH] = "<<~/",
  [sym_sigil_body] = "sigil_body",
  [aux_sym_fenced_block_token1] = "fence_open",
  [aux_sym_fenced_block_token2] = "fence_line",
  [aux_sym_fenced_block_token3] = "fence_close",
  [sym_heading] = "heading",
  [sym_comment] = "comment",
  [sym_blank_line] = "blank_line",
  [sym_text_line] = "text_line",
  [sym_document] = "document",
  [sym__block] = "_block",
  [sym_ahu_block] = "ahu_block",
  [sym_sigil] = "sigil",
  [sym_sigil_close] = "sigil_close",
  [sym_fenced_block] = "fenced_block",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_fenced_block_repeat1] = "fenced_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_LT_TILDE] = anon_sym_LT_LT_TILDE,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [anon_sym_LT_LT_TILDE_SLASH] = anon_sym_LT_LT_TILDE_SLASH,
  [sym_sigil_body] = sym_sigil_body,
  [aux_sym_fenced_block_token1] = aux_sym_fenced_block_token1,
  [aux_sym_fenced_block_token2] = aux_sym_fenced_block_token2,
  [aux_sym_fenced_block_token3] = aux_sym_fenced_block_token3,
  [sym_heading] = sym_heading,
  [sym_comment] = sym_comment,
  [sym_blank_line] = sym_blank_line,
  [sym_text_line] = sym_text_line,
  [sym_document] = sym_document,
  [sym__block] = sym__block,
  [sym_ahu_block] = sym_ahu_block,
  [sym_sigil] = sym_sigil,
  [sym_sigil_close] = sym_sigil_close,
  [sym_fenced_block] = sym_fenced_block,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_fenced_block_repeat1] = aux_sym_fenced_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_LT_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_LT_TILDE_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_sigil_body] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_fenced_block_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_fenced_block_token2] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_fenced_block_token3] = {
    .visible = true,
    .named = true,
  },
  [sym_heading] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_blank_line] = {
    .visible = true,
    .named = true,
  },
  [sym_text_line] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [sym_ahu_block] = {
    .visible = true,
    .named = true,
  },
  [sym_sigil] = {
    .visible = true,
    .named = true,
  },
  [sym_sigil_close] = {
    .visible = true,
    .named = true,
  },
  [sym_fenced_block] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fenced_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_close = 2,
  field_info = 3,
  field_line = 4,
  field_open = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_close] = "close",
  [field_info] = "info",
  [field_line] = "line",
  [field_open] = "open",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_line, 0},
  [1] =
    {field_info, 0},
  [2] =
    {field_close, 1},
    {field_open, 0},
  [4] =
    {field_body, 1},
  [5] =
    {field_info, 0},
    {field_line, 1, .inherited = true},
  [7] =
    {field_line, 0, .inherited = true},
    {field_line, 1, .inherited = true},
  [9] =
    {field_close, 2},
    {field_open, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 2,
  [6] = 6,
  [7] = 7,
  [8] = 7,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 10,
  [16] = 16,
  [17] = 11,
  [18] = 13,
  [19] = 19,
  [20] = 14,
  [21] = 9,
  [22] = 12,
  [23] = 19,
  [24] = 16,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 27,
  [29] = 26,
  [30] = 30,
  [31] = 30,
  [32] = 32,
  [33] = 32,
  [34] = 34,
  [35] = 35,
  [36] = 35,
  [37] = 37,
  [38] = 38,
  [39] = 38,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      if (lookahead == '\n') ADVANCE(27);
      if (lookahead == '#') ADVANCE(32);
      if (lookahead == '<') ADVANCE(30);
      if (lookahead == '>') ADVANCE(35);
      if (lookahead == '`') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead == '`') ADVANCE(9);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(4);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(6);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 5:
      if (lookahead == '>') ADVANCE(16);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(26);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 8:
      if (lookahead == '`') ADVANCE(22);
      END_STATE();
    case 9:
      if (lookahead == '`') ADVANCE(8);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 10:
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(18);
      END_STATE();
    case 11:
      if (eof) ADVANCE(13);
      if (lookahead == '\n') ADVANCE(27);
      if (lookahead == '#') ADVANCE(32);
      if (lookahead == '<') ADVANCE(30);
      if (lookahead == '`') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 12:
      if (eof) ADVANCE(13);
      if (lookahead == '\n') ADVANCE(27);
      if (lookahead == '#') ADVANCE(32);
      if (lookahead == '<') ADVANCE(31);
      if (lookahead == '`') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LT_LT_TILDE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LT_LT_TILDE);
      if (lookahead == '/') ADVANCE(17);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LT_LT_TILDE_SLASH);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_sigil_body);
      if (lookahead == '>') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_fenced_block_token1);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_fenced_block_token2);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_fenced_block_token3);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_fenced_block_token3);
      if (lookahead == '\n') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_heading);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_heading);
      if (lookahead == '\n') ADVANCE(23);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(25);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_blank_line);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_text_line);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(28);
      if (lookahead == '!') ADVANCE(34);
      if (lookahead == '<') ADVANCE(40);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(28);
      if (lookahead == '!') ADVANCE(34);
      if (lookahead == '<') ADVANCE(41);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(28);
      if (lookahead == '#') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(28);
      if (lookahead == '-') ADVANCE(44);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(28);
      if (lookahead == '-') ADVANCE(33);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(28);
      if (lookahead == '>') ADVANCE(16);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(28);
      if (lookahead == '`') ADVANCE(22);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(28);
      if (lookahead == '`') ADVANCE(36);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(28);
      if (lookahead == '`') ADVANCE(46);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(28);
      if (lookahead == '`') ADVANCE(38);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(28);
      if (lookahead == '~') ADVANCE(15);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(28);
      if (lookahead == '~') ADVANCE(14);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(28);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(47);
      if (lookahead == '-') ADVANCE(45);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(47);
      if (lookahead == '-') ADVANCE(43);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(47);
      if (lookahead == '>') ADVANCE(26);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(19);
      if (lookahead != 0) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 12},
  [2] = {.lex_state = 11},
  [3] = {.lex_state = 11},
  [4] = {.lex_state = 11},
  [5] = {.lex_state = 11},
  [6] = {.lex_state = 12},
  [7] = {.lex_state = 11},
  [8] = {.lex_state = 12},
  [9] = {.lex_state = 11},
  [10] = {.lex_state = 11},
  [11] = {.lex_state = 11},
  [12] = {.lex_state = 12},
  [13] = {.lex_state = 12},
  [14] = {.lex_state = 12},
  [15] = {.lex_state = 11},
  [16] = {.lex_state = 12},
  [17] = {.lex_state = 12},
  [18] = {.lex_state = 11},
  [19] = {.lex_state = 11},
  [20] = {.lex_state = 11},
  [21] = {.lex_state = 11},
  [22] = {.lex_state = 11},
  [23] = {.lex_state = 12},
  [24] = {.lex_state = 11},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 7},
  [31] = {.lex_state = 7},
  [32] = {.lex_state = 7},
  [33] = {.lex_state = 7},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 7},
  [36] = {.lex_state = 7},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 7},
  [39] = {.lex_state = 7},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_LT_TILDE] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_LT_LT_TILDE_SLASH] = ACTIONS(1),
    [aux_sym_fenced_block_token3] = ACTIONS(1),
    [sym_heading] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_blank_line] = ACTIONS(1),
    [sym_text_line] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(37),
    [sym__block] = STATE(6),
    [sym_ahu_block] = STATE(6),
    [sym_sigil] = STATE(2),
    [sym_fenced_block] = STATE(6),
    [aux_sym_document_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LT_LT_TILDE] = ACTIONS(5),
    [aux_sym_fenced_block_token1] = ACTIONS(7),
    [sym_heading] = ACTIONS(9),
    [sym_comment] = ACTIONS(9),
    [sym_blank_line] = ACTIONS(9),
    [sym_text_line] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym__block] = STATE(4),
    [sym_ahu_block] = STATE(4),
    [sym_sigil] = STATE(5),
    [sym_sigil_close] = STATE(23),
    [sym_fenced_block] = STATE(4),
    [aux_sym_document_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(13),
    [anon_sym_LT_LT_TILDE] = ACTIONS(15),
    [anon_sym_LT_LT_TILDE_SLASH] = ACTIONS(18),
    [aux_sym_fenced_block_token1] = ACTIONS(20),
    [sym_heading] = ACTIONS(23),
    [sym_comment] = ACTIONS(23),
    [sym_blank_line] = ACTIONS(23),
    [sym_text_line] = ACTIONS(26),
  },
  [STATE(3)] = {
    [sym__block] = STATE(7),
    [sym_ahu_block] = STATE(7),
    [sym_sigil] = STATE(5),
    [sym_sigil_close] = STATE(24),
    [sym_fenced_block] = STATE(7),
    [aux_sym_document_repeat1] = STATE(7),
    [anon_sym_LT_LT_TILDE] = ACTIONS(29),
    [anon_sym_LT_LT_TILDE_SLASH] = ACTIONS(31),
    [aux_sym_fenced_block_token1] = ACTIONS(33),
    [sym_heading] = ACTIONS(35),
    [sym_comment] = ACTIONS(35),
    [sym_blank_line] = ACTIONS(35),
    [sym_text_line] = ACTIONS(37),
  },
  [STATE(4)] = {
    [sym__block] = STATE(7),
    [sym_ahu_block] = STATE(7),
    [sym_sigil] = STATE(5),
    [sym_sigil_close] = STATE(16),
    [sym_fenced_block] = STATE(7),
    [aux_sym_document_repeat1] = STATE(7),
    [anon_sym_LT_LT_TILDE] = ACTIONS(29),
    [anon_sym_LT_LT_TILDE_SLASH] = ACTIONS(18),
    [aux_sym_fenced_block_token1] = ACTIONS(33),
    [sym_heading] = ACTIONS(35),
    [sym_comment] = ACTIONS(35),
    [sym_blank_line] = ACTIONS(35),
    [sym_text_line] = ACTIONS(37),
  },
  [STATE(5)] = {
    [sym__block] = STATE(3),
    [sym_ahu_block] = STATE(3),
    [sym_sigil] = STATE(5),
    [sym_sigil_close] = STATE(19),
    [sym_fenced_block] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [anon_sym_LT_LT_TILDE] = ACTIONS(15),
    [anon_sym_LT_LT_TILDE_SLASH] = ACTIONS(39),
    [aux_sym_fenced_block_token1] = ACTIONS(20),
    [sym_heading] = ACTIONS(42),
    [sym_comment] = ACTIONS(42),
    [sym_blank_line] = ACTIONS(42),
    [sym_text_line] = ACTIONS(45),
  },
  [STATE(6)] = {
    [sym__block] = STATE(8),
    [sym_ahu_block] = STATE(8),
    [sym_sigil] = STATE(2),
    [sym_fenced_block] = STATE(8),
    [aux_sym_document_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(48),
    [anon_sym_LT_LT_TILDE] = ACTIONS(5),
    [aux_sym_fenced_block_token1] = ACTIONS(7),
    [sym_heading] = ACTIONS(50),
    [sym_comment] = ACTIONS(50),
    [sym_blank_line] = ACTIONS(50),
    [sym_text_line] = ACTIONS(52),
  },
  [STATE(7)] = {
    [sym__block] = STATE(7),
    [sym_ahu_block] = STATE(7),
    [sym_sigil] = STATE(5),
    [sym_fenced_block] = STATE(7),
    [aux_sym_document_repeat1] = STATE(7),
    [anon_sym_LT_LT_TILDE] = ACTIONS(54),
    [anon_sym_LT_LT_TILDE_SLASH] = ACTIONS(57),
    [aux_sym_fenced_block_token1] = ACTIONS(59),
    [sym_heading] = ACTIONS(62),
    [sym_comment] = ACTIONS(62),
    [sym_blank_line] = ACTIONS(62),
    [sym_text_line] = ACTIONS(65),
  },
  [STATE(8)] = {
    [sym__block] = STATE(8),
    [sym_ahu_block] = STATE(8),
    [sym_sigil] = STATE(2),
    [sym_fenced_block] = STATE(8),
    [aux_sym_document_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(57),
    [anon_sym_LT_LT_TILDE] = ACTIONS(68),
    [aux_sym_fenced_block_token1] = ACTIONS(71),
    [sym_heading] = ACTIONS(74),
    [sym_comment] = ACTIONS(74),
    [sym_blank_line] = ACTIONS(74),
    [sym_text_line] = ACTIONS(77),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(82), 2,
      anon_sym_LT_LT_TILDE,
      sym_text_line,
    ACTIONS(80), 6,
      ts_builtin_sym_end,
      anon_sym_LT_LT_TILDE_SLASH,
      aux_sym_fenced_block_token1,
      sym_heading,
      sym_comment,
      sym_blank_line,
  [13] = 2,
    ACTIONS(86), 2,
      anon_sym_LT_LT_TILDE,
      sym_text_line,
    ACTIONS(84), 6,
      ts_builtin_sym_end,
      anon_sym_LT_LT_TILDE_SLASH,
      aux_sym_fenced_block_token1,
      sym_heading,
      sym_comment,
      sym_blank_line,
  [26] = 2,
    ACTIONS(88), 2,
      anon_sym_LT_LT_TILDE,
      sym_text_line,
    ACTIONS(90), 5,
      anon_sym_LT_LT_TILDE_SLASH,
      aux_sym_fenced_block_token1,
      sym_heading,
      sym_comment,
      sym_blank_line,
  [38] = 2,
    ACTIONS(94), 1,
      sym_text_line,
    ACTIONS(92), 6,
      ts_builtin_sym_end,
      anon_sym_LT_LT_TILDE,
      aux_sym_fenced_block_token1,
      sym_heading,
      sym_comment,
      sym_blank_line,
  [50] = 2,
    ACTIONS(98), 1,
      sym_text_line,
    ACTIONS(96), 6,
      ts_builtin_sym_end,
      anon_sym_LT_LT_TILDE,
      aux_sym_fenced_block_token1,
      sym_heading,
      sym_comment,
      sym_blank_line,
  [62] = 2,
    ACTIONS(102), 1,
      sym_text_line,
    ACTIONS(100), 6,
      ts_builtin_sym_end,
      anon_sym_LT_LT_TILDE,
      aux_sym_fenced_block_token1,
      sym_heading,
      sym_comment,
      sym_blank_line,
  [74] = 2,
    ACTIONS(86), 2,
      anon_sym_LT_LT_TILDE,
      sym_text_line,
    ACTIONS(84), 5,
      anon_sym_LT_LT_TILDE_SLASH,
      aux_sym_fenced_block_token1,
      sym_heading,
      sym_comment,
      sym_blank_line,
  [86] = 2,
    ACTIONS(106), 1,
      sym_text_line,
    ACTIONS(104), 6,
      ts_builtin_sym_end,
      anon_sym_LT_LT_TILDE,
      aux_sym_fenced_block_token1,
      sym_heading,
      sym_comment,
      sym_blank_line,
  [98] = 2,
    ACTIONS(88), 1,
      sym_text_line,
    ACTIONS(90), 6,
      ts_builtin_sym_end,
      anon_sym_LT_LT_TILDE,
      aux_sym_fenced_block_token1,
      sym_heading,
      sym_comment,
      sym_blank_line,
  [110] = 2,
    ACTIONS(98), 2,
      anon_sym_LT_LT_TILDE,
      sym_text_line,
    ACTIONS(96), 5,
      anon_sym_LT_LT_TILDE_SLASH,
      aux_sym_fenced_block_token1,
      sym_heading,
      sym_comment,
      sym_blank_line,
  [122] = 2,
    ACTIONS(108), 2,
      anon_sym_LT_LT_TILDE,
      sym_text_line,
    ACTIONS(110), 5,
      anon_sym_LT_LT_TILDE_SLASH,
      aux_sym_fenced_block_token1,
      sym_heading,
      sym_comment,
      sym_blank_line,
  [134] = 2,
    ACTIONS(102), 2,
      anon_sym_LT_LT_TILDE,
      sym_text_line,
    ACTIONS(100), 5,
      anon_sym_LT_LT_TILDE_SLASH,
      aux_sym_fenced_block_token1,
      sym_heading,
      sym_comment,
      sym_blank_line,
  [146] = 2,
    ACTIONS(82), 2,
      anon_sym_LT_LT_TILDE,
      sym_text_line,
    ACTIONS(80), 5,
      anon_sym_LT_LT_TILDE_SLASH,
      aux_sym_fenced_block_token1,
      sym_heading,
      sym_comment,
      sym_blank_line,
  [158] = 2,
    ACTIONS(94), 2,
      anon_sym_LT_LT_TILDE,
      sym_text_line,
    ACTIONS(92), 5,
      anon_sym_LT_LT_TILDE_SLASH,
      aux_sym_fenced_block_token1,
      sym_heading,
      sym_comment,
      sym_blank_line,
  [170] = 2,
    ACTIONS(108), 1,
      sym_text_line,
    ACTIONS(110), 6,
      ts_builtin_sym_end,
      anon_sym_LT_LT_TILDE,
      aux_sym_fenced_block_token1,
      sym_heading,
      sym_comment,
      sym_blank_line,
  [182] = 2,
    ACTIONS(106), 2,
      anon_sym_LT_LT_TILDE,
      sym_text_line,
    ACTIONS(104), 5,
      anon_sym_LT_LT_TILDE_SLASH,
      aux_sym_fenced_block_token1,
      sym_heading,
      sym_comment,
      sym_blank_line,
  [194] = 3,
    ACTIONS(112), 1,
      aux_sym_fenced_block_token2,
    ACTIONS(115), 1,
      aux_sym_fenced_block_token3,
    STATE(25), 1,
      aux_sym_fenced_block_repeat1,
  [204] = 3,
    ACTIONS(117), 1,
      aux_sym_fenced_block_token2,
    ACTIONS(119), 1,
      aux_sym_fenced_block_token3,
    STATE(25), 1,
      aux_sym_fenced_block_repeat1,
  [214] = 3,
    ACTIONS(117), 1,
      aux_sym_fenced_block_token2,
    ACTIONS(121), 1,
      aux_sym_fenced_block_token3,
    STATE(26), 1,
      aux_sym_fenced_block_repeat1,
  [224] = 3,
    ACTIONS(117), 1,
      aux_sym_fenced_block_token2,
    ACTIONS(123), 1,
      aux_sym_fenced_block_token3,
    STATE(29), 1,
      aux_sym_fenced_block_repeat1,
  [234] = 3,
    ACTIONS(117), 1,
      aux_sym_fenced_block_token2,
    ACTIONS(125), 1,
      aux_sym_fenced_block_token3,
    STATE(25), 1,
      aux_sym_fenced_block_repeat1,
  [244] = 2,
    ACTIONS(127), 1,
      anon_sym_GT_GT,
    ACTIONS(129), 1,
      sym_sigil_body,
  [251] = 2,
    ACTIONS(131), 1,
      anon_sym_GT_GT,
    ACTIONS(133), 1,
      sym_sigil_body,
  [258] = 2,
    ACTIONS(135), 1,
      anon_sym_GT_GT,
    ACTIONS(137), 1,
      sym_sigil_body,
  [265] = 2,
    ACTIONS(139), 1,
      anon_sym_GT_GT,
    ACTIONS(141), 1,
      sym_sigil_body,
  [272] = 1,
    ACTIONS(143), 2,
      aux_sym_fenced_block_token2,
      aux_sym_fenced_block_token3,
  [277] = 1,
    ACTIONS(145), 1,
      anon_sym_GT_GT,
  [281] = 1,
    ACTIONS(147), 1,
      anon_sym_GT_GT,
  [285] = 1,
    ACTIONS(149), 1,
      ts_builtin_sym_end,
  [289] = 1,
    ACTIONS(151), 1,
      anon_sym_GT_GT,
  [293] = 1,
    ACTIONS(153), 1,
      anon_sym_GT_GT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 13,
  [SMALL_STATE(11)] = 26,
  [SMALL_STATE(12)] = 38,
  [SMALL_STATE(13)] = 50,
  [SMALL_STATE(14)] = 62,
  [SMALL_STATE(15)] = 74,
  [SMALL_STATE(16)] = 86,
  [SMALL_STATE(17)] = 98,
  [SMALL_STATE(18)] = 110,
  [SMALL_STATE(19)] = 122,
  [SMALL_STATE(20)] = 134,
  [SMALL_STATE(21)] = 146,
  [SMALL_STATE(22)] = 158,
  [SMALL_STATE(23)] = 170,
  [SMALL_STATE(24)] = 182,
  [SMALL_STATE(25)] = 194,
  [SMALL_STATE(26)] = 204,
  [SMALL_STATE(27)] = 214,
  [SMALL_STATE(28)] = 224,
  [SMALL_STATE(29)] = 234,
  [SMALL_STATE(30)] = 244,
  [SMALL_STATE(31)] = 251,
  [SMALL_STATE(32)] = 258,
  [SMALL_STATE(33)] = 265,
  [SMALL_STATE(34)] = 272,
  [SMALL_STATE(35)] = 277,
  [SMALL_STATE(36)] = 281,
  [SMALL_STATE(37)] = 285,
  [SMALL_STATE(38)] = 289,
  [SMALL_STATE(39)] = 293,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block, 1, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__block, 1, 0, 0), SHIFT(31),
  [18] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__block, 1, 0, 0), SHIFT(28),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__block, 1, 0, 0), SHIFT(4),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__block, 1, 0, 0), SHIFT(4),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__block, 1, 0, 0), SHIFT(33),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__block, 1, 0, 0), SHIFT(3),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__block, 1, 0, 0), SHIFT(3),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sigil, 3, 0, 4),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sigil, 3, 0, 4),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sigil, 2, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sigil, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sigil_close, 3, 0, 4),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sigil_close, 3, 0, 4),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fenced_block, 3, 0, 5),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fenced_block, 3, 0, 5),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fenced_block, 2, 0, 2),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fenced_block, 2, 0, 2),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sigil_close, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sigil_close, 2, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ahu_block, 3, 0, 7),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ahu_block, 3, 0, 7),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ahu_block, 2, 0, 3),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ahu_block, 2, 0, 3),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fenced_block_repeat1, 2, 0, 6), SHIFT_REPEAT(34),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fenced_block_repeat1, 2, 0, 6),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fenced_block_repeat1, 1, 0, 1),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [149] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_memetic_wikitext(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
